language: go
sudo: required
services:
- docker
before_install:
- docker pull golang:alpine
install:
- make
script:
- export IMAGE_NAME=gableroux/gothub
- docker build -f Dockerfile -t $IMAGE_NAME:$COMMIT .
deploy:
  provider: script
  script:
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:latest
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - docker push "${IMAGE_NAME}:latest"
  - docker push "${IMAGE_NAME}:${COMMIT}"
  on:
    branch: master
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: jKDYZVj/wNz08ALDW9AHkeMyLrIMP6iCiNc2exRulC1N250fVpLpwrIeXjQ1E/vfwaHUUMKwZ9fl4zSCxOQnMIgClxv99C63r9/L9zRp1rHst0DW7HRlaym1IYeZrDw2kMJ+oH3a0GgqqBK9s9K11Ph8riIVD3ipok4OcVrNI8M1brfiPYVPSN10hjAhhRi2ol+AUImwKrKoq/WyAAbn4TR/AHHU1X9aa767d8PgWamUeM0rwJlegCFgCgZEZFcV3oYztXk8Xrt3GXVlhzOLfoJxM6PPGFu1wCPhXE8qk2jOVhEcaRWbN7ZUAzZ0xe8gerueemmE1m/C0zWwGAr4mrFZEJFSy4fKyBRidPdFPenkZHdlVG1ywBXHRZsk/107te4Swhl08hKaMol5Z479BUol7d7AMYY7vP/6Twwq7kiJbyVZneLMps9VgmTTT68jKLGs0OqqR53v5vVa5e3+4m38K2WzMJPwk266bRKHc95Q42hnf3JyQBoqcEqJoXW6ApacdorHSJ400pnCcJ7WR6ueVPbxNFj2rB4ryhfuFVuoz7YitflJADC+JD2hruVPqzNw3KWLkDy0/uf94vcCUbubrQpS9euVzUj5P7N4Y4wDQbQFuNUuXxFdCNUCJ0ZCLKlpiV15L+j2S4r72sfC/Nz41SSDI6uXRSb0INpO6ik=
  - secure: m/iyTsWFgoamDlSAviSLIG7DKofXmTS8cj6BErRAl28Fsy14TnqTp5g2TA4jeA1hDDNyYYxbOsJUPoR/rQHQtT6m27jIWOXx0Yz+zPctjkv4gDZTaGTXko7Dm3UZm+ruIrVhZwXKAvb+A9DN6KDWZGrPdueSfzKBqKG0klUbabhhVA0JGI7EGN7UdfNNqXesh9KRF5sErp1lH0EfOUUv++RUJ4Lzva3FwE3VgbB6WrPVjh7vDV55EHo/OLc1MlBCDpJCK8C7758uUnGVPBRF67u3GvvyxX8SMuf5RJCqLVMc2vsSUsRO0J2x+HK690I8hxZKg3SDBOCnvEewSe/vi0Gls/FgqGIOON16SYggaGrkKM1nwhS7h8gYL8546HTOe3D1tdngTTmvdalBK+NM2fxT4MVUh2cqzoXol7bt5T4XFyEMcl1Ka/C0cJIlJnAQ8Hw2Ye+XWl83b3W1JPsDnChcScq69q/87NRN31gZ/BA7SiUjcl3GWbIJ45WmEJKCyrk/qzJcHdNl0vEFCVX6lNi/Edy9cQrYkYal8MjvPMxZWVZFQChgD1QCA9dOj8ijnI4wgeKJqeG5NoAkbJUjBF39APXTAw2wDCJLsF+oZSFbufP5FzQyJ0qEXiqxEjkGwTF7Wq3+lKM9E/o02kKlVqWVFZs9LbO9Y5r7jY6duUQ=
