language: go
sudo: required
services:
- docker
before_install:
- docker pull golang:alpine
install:
- make
script:
- export REPO=$DOCKER_USER/gothub
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then 
    echo "latest"; 
  else 
    echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: lNXn4mOHmm/cKTFYOAmJB9Ax6FK2uSFhQHC11x7TeFSbnT6LFcavpwP7pReBUXGhJPEZ4FtW3eFetGffISn7Xd6/8MPzKVVBmVEdQO3xgPVgms7p8k6aisTXShXMQFuC7NAk9i2iJ8zVwF7XXNo7axHK5kllQm29k4oq33Qu3fPqsUSzZCmIvNI8ni4VEsx5mNc2f/g57+qNHDi79IjPiQbrWdOjK/HL789ZCjtDyBEP+y/Zy9qkFB3aDivVxuS6lKmuWjI1Lw/yz7dJNwVGGITHcZ4lAynxmlmDxKGnAJzjkDVpfNJbBLuYPsXBmv/U+1xDwK31dC4IDbKYdMrLiRXUMks1tgmKwt/7M0FE2TJoFKXuErAhJ58s3cTR/6rZLm4ShltuIzraM6OVLOlIc/8joi5eRI4+0da2md3dHeMsNUafiMSq7A2MTghDlYyIk8dEuNvYokwzEsdt1B/7bZVE79jMen8QPWD5K4dx81BpLfCOsf6+9FlE4Hc12TpiKULX/w8mzEKQftp2p3tvw1JpCXzf68ZnX3s7528hvEyh/wdKhxjaC0Dpk5up7zv9P8z3Zw9FSJhU2asT9/Ys1hVPfYfyyLz1xyCoixoRSAWwCM6pgWWQDD4YhR7sh5NzzsOfXPeshrLRwuYmNdeZCTNWh4hcwDiYsZaKgwFNP2I=
  - secure: Gn7aFbkf66ax+0fE9HW6EYOQB9RDXeIWsT+dy0a6uQqxbsvrK39/h16BZ5pJ1kQ3s+QRvAqlOvPYHLurPgG3HtimqEesTWpAPfxaCOPCBM+LrjHh+IATmfccKqMvVC5FGzae3Y91nPxnRfEXcQgzq+MYYD1Pchv6Ib8voV3CFvhl8/jMAvb43nmkl1TXTaadROviIXjOAWW7Jmx1pWRYW6loj4GFoEkj5YbTdTeQahDz7fYgs3gqJoiUDZE4eGE31KvRa6neRTKAdsEizR5lPlEdpHtPxj34lXh/t2M7HrnrzrdwE529UUtvJDi2WYN4Bn4kfqop2Nw/KGnGrnmdjC3OCslHDdtrQzFxdd7SlhZSYwFdoPJ+tXVPbKWhTd5oHCsheVNa77bQ2LSFIgwUs/QA4RWBuyYsMYMS3hlWTbsXurHZ0MWNPgtMmDJbm+Seam3TgHV99bkCfyai1zDhiOs2TOJ002Tb9SBivSvDusR5oNrwFtMuoHmBNIG2MqY6uNEg1puzLr0ko1rjZrYAEgkLoAqdHb7jl1VKNlND1GB6/+s26cEdyXfQ908GM3JBSPWy6i8VNCL6dIim2F7qjSXE78l5w3dcQyoccaHVy05KRqy6Hi6rIF0BKivXg1mhNY66urjExF7lQqaTaSUu3dauNv7TerbCMlnNRM6WhxY=
  - secure: N0DrpOflHluhuH2TV1TbywMCWl0ZE3z18kLtmljziHQ3L1XSS5ISqaQKRgjBnZGR9sssi1Y4/fRzUObFpgge7XbLaycyWteRMjD1pBNtC1BGQkeWE7kc2WwJUdjks3+xx5VGamtXtdiP9Sy/WJleCexnu0v9TrXS0UPJqWVQab+8clLW17E53VAvo3FTu2W4oGHfiGVGR3swQNjH4m6teb/d8IOwNH2cE2fUzOmj4DLqU/pvrMZdCL+U1mJ92mIFtkTSEkSXxuijhqF8cWPzdbzlb+JRAXPwoTDUrLbqBnU/GBo2s9MOzyP3h/V1lSSZ3gaywCo3t63MN5lPUMSZxEPLHO3CYmKSmuaIsD1QXSZtA5kmN3zYbBJsLBwcBkR6KuljmHpkmueGACe/L4tQerrsnDPXo1ZQtMQJZ+PB7g4Dk+39RobzWqO5lgy4JHiTbCHbip+qqD+vgb3WxncI/wHS3RcIZIfxLXi2D/XlZl+tTIASvogDnbqP6BOpV+b9zi+sT3gMeJYR7bopAA9h4ah/BI+q5clszZOO9D3Wcy50v082kU4wE9O1bV/5ifbmOcINb8YgV4eDhZBU/X0RzXAQgzhAtw7AAy/NYPGUPws6CFEXaF/w4n3r4yEKzDFmyMd7DR3E8gq+2Zq5qgSIUsXV+FaPacHuojswdPeGByg=
