language: go
sudo: required
services:
- docker
before_install:
- docker pull golang:alpine
install:
- make
script:
- export REPO=$DOCKER_USER/gothub
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push $REPO:$TAG
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: FfhRSwjJnLhXyHALk6k91+xXPqfn/UStyaBVLvXyW5Vm5fN8/0rBHO2HMAnAJbOUPDdfUltr7c/5if5PstIRNs6Aro9VnGLvkr7hxdlFJPCahwOMvjYMZkhID4VTGnHuei743QnJE0egYyx7aJN5/2FGdc7e+CwzcPVAn4e9sJ/mWKQzurCqrmNrJuRrP4P5LZHPeLcMwka/U4JP5I+MZBahRD/6wXYLVbLvTl9n9+082pvrlhU/QYB4rWl2tPQVMBCPicDidqCSkX152fMWlQekc8rRGFNGVzdvM1hhB3DoocmzfrkX+i3aHxcrM6xJKFloqJv3ICEKApc2Df/gfOS+QKRvmEHNqdV7wJM7o3m7UlRSPoNa4W5eiAVuaGHo8s/LWMicKMsI5khMC7pXYLzj91FpcF94DriG3b1aR7dewFVnyn8ohaBmDdg8Jg9EXtS45U35bqAt3lPJ1gCODA/AyNrB+WWEbJWjLW5EdX46/6153rlnzbZ344BMg3wZFrTyQB9xSIms2EPV/kpRijDWDYcVBuz0etdRE4CpZXK4zZ08GzKg1Tg3W7EPaVgBgwvsT3EU15Y3/6QCkpATqiGhmt1DjCBCKWTGCp6DC1y132zyOHvWF6ypyJOJA1vF9OZ1D08r9fuuLgnYdFPEONoGYxTOFAQeFgWxZpZncgY=
  - secure: PwtDKtqWtIo01QsMXGBh8DtDr65bOXTxlhuaJwOc7w/vLq+q3tYtp8Xjq5JhusSqBRg0iIZ8BVYt8jTVTN9cN7VNXBy8Gl5Wlnaa0P3seTuitg/REQzgB9TM3vc2g2D6hAQJU/sD1xedwWL5tsHKPcRjwBrAZNDH/om4dgmVXH9STrO3GFMudFUOOcRrZtrUwY/fEM8kZ5FNen8COhpB7gW1FhYrwvGXmseU1tYt3dzP6ABjls39rj7OmI2u8nQBOf5zbYNJsQ/2y6DDpJUnSNdkqyfaI7i4LxtutqxYS78rORrHqx3rVeJjGGItj0lBpmDUk20pCdMQKdVBSGFiHDCN7WFUOprD33Qucq06fM8ap9VxVq3QDzZR0Y/OWQfaLs4weUZEeybfGsr0tFEuanYY96lS/xUKNHj6scCc6U0guZThG+e4zf+w4SLLEm0eLAUsLTj5SKgpqR2o3TvSuTJILfF4K09USqTgByj5zxgydBR1hcEETjvnY3rviVGIQF68WJkeuj6HnZV9L1sfLBD4mjXXxme6V5imxzLKaPqqZICzVRr5T/Uj/oW8qBU59KsarT5nCH4uU6ytLsP2Uz+72l63psVWmII5Uu/Fwy/oAYP7ATGKqErCr1Zj3rgrlf1skfWGmKFc/E8GbhFSw4jr2p5VcW5MXPIefnhDhxQ=
  - secure: oW4vts3EcE7/QAaHP0HvyLhpmxe2SncEXeLcxq+y8YVwA4PVSre4IOWDa0a3pz3zAGf/cJ+HkkX4VPrL4zQSwUDJjFFEeUv/g//qXloM1Xac4/8a45hSqZT6zipwLJtfmorlcW9TGI29reW85lkP4hbxW1I87w9JMoMDqcQh0vZ9cOYz9DqxhdgcHe2mAhH8qVylNGv9HdmJdgIXlxYhG4ogylrZVXUCNo57NqMV878o5wi5qqdSwzZz/Zqr6HXwoQQLFOV9U6yPLueG9nSZUzwODBIE028hdpOmvLcwt9eIt8KItvxUebn5N95fSvboMSwAHCtsmu9Cvl9hOwUjKbCyBXVG/+VKzIRj1qW21/FSzECaYK/4E1OyAM54VkmWXoiA8rsM1NUxaHtvZSSAXrLq73Yrnw7re+grKzn9sgV93pVldISeRmyiCqRrpFLc4+1F2jpKDwNFa4+0mX8tAeRKgsdPM8IQHz71HQ6/E2k45cAJQqZ1YtTYntBGaJY2WrDuLB/XMfePHOVNsJu/ypKKZobSsIuDx9Uq4CIUIbWzIKzH6KpttKOe/nbNEQNzkO9T6jimvb9vgkiiRvGILpLWwum6P/CQEYI+NPFmV8Ow4a4fz2mVkXch8/zA2QuEc9Z2Hc+X3JQranoLTRw4pNJch1dbVTRA2eGKguxRb4M=
